import os
import json
import re
from mistralai import Mistral
from fpdf import FPDF
from dotenv import load_dotenv

import agent_1
import run_agent2

load_dotenv()

MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

SYSTEM_PROMPT = """You are a computational structural biologist assisting in protein misfolding risk analysis.

You have access to the following tools:

1. run_esm_agent(sequence)
   - Generates 3Di structural tokens
   - Computes latent Z-score

2. run_severity_checker(structural_tokens)
   - Returns severity label and probability

EXECUTION POLICY:

- If Z-score and 3di sequence are NOT provided in the input, you MUST call run_esm_agent.
- If no severity classification is provided, you MUST call run_severity_checker.
- You MUST NOT generate structural analysis before receiving run_esm_agent and run_severity_checker results .
- After all required tools return, generate the final structural report.
- Never fabricate tool outputs.
- Never assume tool outputs.
- Wait for tool responses before continuing.

You do NOT invent experimental results.
You only reason from:
- The provided amino acid sequence
- The anomaly Z-score
- The severity classification
- The retrieved homolog information

If information is insufficient, explicitly state uncertainty.

Your task is to generate a mechanistic structural interpretation of why the protein may be destabilized, grounded in known protein folding principles.
"""

tools = [
    {
        "type": "function",
        "function": {
            "name": "run_esm_agent",
            "description": "Generates 3Di structural tokens and computes latent Z-score",
            "parameters": {
                "type": "object",
                "required": ["sequence", "name"],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The specific name of the protein whose structure is being analyzed."
                    },
                    "sequence": {
                        "type": "string",
                        "description": "A string of characters used to describe the protein structure that needs to be passed."
                    }
                }
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "run_severity_checker",
            "description": "Returns severity label and probability",
            "parameters": {
                "type": "object",
                "required": ["z_score", "original_sequence", "sequence_3di"],
                "properties": {
                    "sequence_3di": {
                        "type": "string",
                        "description": "The 3di tokens generated by run_esm_agent"
                    },
                    "z_score": {
                        "type": "string",
                        "description": "The Z-score calculated by run_esm_agent"
                    },
                    "original_sequence": {
                        "type": "string",
                        "description": "The original sequence of characters provided by the user."
                    }
                }
            }
        }
    }
]

def generate_pdf_report(report_data, output_file="ClassificationResults.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Protein Misfolding Risk Analysis Report", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Summary:", ln=True)
    pdf.set_font("Arial", size=12)
    raw_text = report_data.get("output", {}).get("raw_text", "")
    
    def sanitize_text(text):
        if not isinstance(text, str):
            text = str(text)
        text = text.replace("Δ", "Delta ")
        text = text.replace("Î”", "Delta ")
        
        # Break long strings (like sequences) to prevent FPDF "Not enough horizontal space" error
        lines = []
        for line in text.split('\n'):
            words = []
            for w in line.split(' '):
                if len(w) > 65:
                    words.extend([w[i:i+65] for i in range(0, len(w), 65)])
                else:
                    words.append(w)
            lines.append(' '.join(words))
        text = '\n'.join(lines)
        
        return text.encode('latin-1', 'replace').decode('latin-1')

    pdf.multi_cell(0, 10, txt=sanitize_text(f"Z-Score: {report_data.get('anomaly_z_score')}"))
    pdf.multi_cell(0, 10, txt=sanitize_text(f"Severity Classification: {report_data.get('severity_classification')}"))
    pdf.multi_cell(0, 10, txt=sanitize_text(f"Homolog Information: {report_data.get('homolog_information', 'N/A')}"))
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Structural Interpretation:", ln=True)
    pdf.set_font("Arial", size=12)
    
    pdf.multi_cell(0, 10, txt=sanitize_text(raw_text))
    
    pdf.output(output_file)
    print(f"\nPDF Report saved as {output_file}")

def _run_orchestrator_loop(protein_name, protein_sequence, output_file="ClassificationResults.pdf"):
    """
    Non-interactive orchestrator loop. Runs the full Mistral tool-calling pipeline
    (Agent 1 -> Agent 2 -> final report) and generates a PDF.

    Returns the absolute path to the generated PDF, or raises on failure.
    """
    client = Mistral(api_key=MISTRAL_API_KEY)

    prompt = f"""Get me information on the following protein {protein_name} with the sequence {protein_sequence}

    Please output your final answer as JSON matching exactly this schema:
    {{
      "type": "object",
      "required": ["output"],
      "properties": {{
        "output": {{
          "type": "object",
          "required": ["raw_text", "timestamp"],
          "properties": {{
            "raw_text": {{"type": "string", "description": "The model's output in raw text"}},
            "timestamp": {{"type": "string", "format": "date-time", "description": "The time of the output"}}
          }}
        }},
        "anomaly_z_score": {{"type": "number", "description": "The anomaly Z-score of the protein"}},
        "homolog_information": {{"type": "string", "description": "The retrieved homolog information of the protein"}},
        "severity_classification": {{"type": "string", "description": "The severity classification of the protein misfolding risk"}}
      }}
    }}"""

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt}
    ]

    print("Starting Orchestrator...")
    while True:
        response = client.chat.complete(
            model="mistral-medium-latest",
            messages=messages,
            tools=tools
        )

        message = response.choices[0].message
        messages.append(message)

        if message.tool_calls:
            for tool_call in message.tool_calls:
                func_name = tool_call.function.name
                args = json.loads(tool_call.function.arguments)

                print(f"\n--- Calling Tool: {func_name} ---")

                if func_name == "run_esm_agent":
                    esm_ag = agent_1.MapperAgent()
                    status_json = esm_ag.run(args['sequence'], args['name'])

                    if status_json.get("status") == "success":
                        result_str = json.dumps({
                            "z_score": str(status_json["z_score"]),
                            "sequence_3di": status_json["sequence_3di"]
                        })
                    else:
                        result_str = json.dumps({"error": status_json.get('message', 'Unknown error')})

                elif func_name == "run_severity_checker":
                    sev_result = run_agent2.run_classification(
                        sequence_3di=args['sequence_3di'],
                        anomaly_z_score=float(args['z_score']),
                        original_sequence=args.get('original_sequence', ''),
                    )
                    result_str = json.dumps(sev_result.to_dict())

                else:
                    result_str = json.dumps({"error": "Unknown tool"})

                print(f"Tool Result: {result_str}")

                messages.append({
                    "role": "tool",
                    "name": func_name,
                    "content": result_str,
                    "tool_call_id": tool_call.id
                })
        else:
            final_content = message.content or ""
            print("\n--- Final Analysis ---")
            print(final_content)

            clean_content = final_content.strip()
            if clean_content.startswith("```json"):
                clean_content = clean_content[7:]
            if clean_content.startswith("```"):
                clean_content = clean_content[3:]
            if clean_content.endswith("```"):
                clean_content = clean_content[:-3]
            clean_content = clean_content.strip()

            report_data = None

            if clean_content:
                json_match = re.search(r'\{[\s\S]*\}', clean_content)
                if json_match:
                    try:
                        report_data = json.loads(json_match.group())
                    except json.JSONDecodeError:
                        print(f"[WARNING] Could not parse JSON from model response")

            if report_data is None:
                report_data = {
                    "output": {"raw_text": final_content or "Analysis could not produce structured output.", "timestamp": ""},
                    "anomaly_z_score": None,
                    "severity_classification": "Unknown",
                    "homolog_information": "N/A",
                }

            generate_pdf_report(report_data, output_file)
            return os.path.abspath(output_file), report_data


def call_orchestrator(protein_name, dna_sequence, output_file="ClassificationResults.pdf"):
    """
    Public entry point for programmatic (server) usage.
    Accepts protein_name and dna_sequence, runs the full pipeline,
    and returns (pdf_path, report_data).
    """
    if not protein_name:
        protein_name = "Unknown_Protein"
    if not dna_sequence:
        raise ValueError("A DNA sequence must be provided.")

    return _run_orchestrator_loop(protein_name, dna_sequence, output_file)


def main():
    print("=== Protein Misfolding Risk Analysis ===")
    protein_name = input("Enter Protein Name (or press Enter for 'Unknown_Protein'): ").strip() or "Unknown_Protein"
    protein_sequence = input("Enter DNA or Amino Acid Sequence: ").strip()

    if not protein_sequence:
        print("Error: A sequence must be provided.")
        return

    try:
        pdf_path, _ = call_orchestrator(protein_name, protein_sequence)
        print(f"\nPDF Report saved at: {pdf_path}")
    except Exception as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()
