from transformers import AutoTokenizer, AutoModel
from Bio.Seq import Seq
from pathlib import Path
import requests
import tempfile
from agent_1.helpers import *
import torch
import re
import os


class MapperAgent:
    def __init__(self, model_name="facebook/esm2_t33_650M_UR50D",
                 baseline_path=None,
                 pdb_output_dir="Saved_PDBs"):
        if baseline_path is None:
            baseline_path = Path(__file__).parent / "baseline_weights" / "latent_space_baseline.pt"

        print("[Agent 1] Initializing Mapper Agent...")
        self.device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu")

        self.pdb_dir = Path(pdb_output_dir)
        self.pdb_dir.mkdir(parents=True, exist_ok=True)
        print(
            f"[Agent 1] PDBs will be saved permanently to: {self.pdb_dir.absolute()}")

        print(f"[Agent 1] Loading ESM-2 on {self.device}...")
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_name, do_lower_case=False, use_fast=True)
        self.model = AutoModel.from_pretrained(model_name).to(self.device)
        self.model.eval()

        if not os.path.exists(baseline_path):
            raise FileNotFoundError(
                f"[Agent 1] Baseline file '{baseline_path}' not found!")
        self.baseline = torch.load(baseline_path, map_location=self.device)
        self.centroid = self.baseline["centroid"].to(self.device)
        self.mean_dist = self.baseline["mean_dist"].to(self.device)
        self.std_dist = self.baseline["std_dist"].to(self.device)

        self.foldseek_bin = find_foldseek()
        print("[Agent 1] Initialization Complete.\n")

    def translate_dna(self, seq: str) -> str:
        """Accept DNA or amino acid sequence. If DNA, translate; if AA, use as-is."""
        sanitize = lambda s: re.sub(r"[UZOB]", "X", s.replace("*", ""))
        try:
            aa_sequence = str(Seq(seq).translate()).replace("*", "")
            return sanitize(aa_sequence)
        except Exception:
            return sanitize(seq)

    def generate_embedding(self, aa_seq: str) -> torch.Tensor:
        inputs = self.tokenizer(aa_seq, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        with torch.no_grad():
            outputs = self.model(**inputs)
        token_embeddings = outputs.last_hidden_state[0][1:-1]
        attention_mask = inputs["attention_mask"][0][1:-1].unsqueeze(-1)
        return (token_embeddings * attention_mask).sum(dim=0) / attention_mask.sum()

    def compute_z_score(self, embedding: torch.Tensor) -> float:
        distance = torch.linalg.norm(embedding - self.centroid)
        z_score = (distance - self.mean_dist) / self.std_dist
        return z_score.item()

    def generate_and_save_pdb(self, aa_seq: str, protein_name: str) -> Path:
        url = "https://api.esmatlas.com/foldSequence/v1/pdb/"
        print(
            f"[Agent 1] Requesting PDB from ESMFold API for {len(aa_seq)} amino acids...")

        response = requests.post(url, data=aa_seq, headers={
                                 "Content-Type": "text/plain"})
        if response.status_code == 200:
            pdb_path = self.pdb_dir / f"{protein_name}.pdb"

            with open(pdb_path, "w") as f:
                f.write(response.text)

            file_size = os.path.getsize(pdb_path)
            if file_size < 100:
                raise RuntimeError(
                    f"ESMFold returned an empty or invalid PDB (Size: {file_size} bytes).")

            with open(pdb_path, "r") as f:
                first_line = f.readline().strip()
                if not first_line.startswith("HEADER") and not first_line.startswith("ATOM"):
                    print(
                        f"\n[FATAL API ERROR] The API did not return a valid PDB. It returned:\n{first_line}")
                    raise RuntimeError("Invalid PDB file generated by API.")

            return pdb_path
        else:
            raise RuntimeError(
                f"ESMFold API failed with status {response.status_code}")

    def convert_pdb_to_3di(self, pdb_path: Path, protein_name: str) -> str:
        """Runs Foldseek on the saved PDB file using a temp dir for junk db files."""
        with tempfile.TemporaryDirectory(prefix="agent1_foldseek_junk_") as tmp_dir:
            work_dir = Path(tmp_dir)
            results = run_foldseek_pdb_to_3di(
                [pdb_path], self.foldseek_bin, work_dir)

            if protein_name in results:
                return results[protein_name]
            else:
                raise ValueError(
                    "Foldseek failed to extract 3Di sequence from the PDB.")

    def run(self, dna_sequence: str, protein_name="target_protein") -> dict:
        print(f"[Agent 1] Processing sequence: {protein_name}")
        try:
            aa_seq = self.translate_dna(dna_sequence)
            print(f"  -> Translated to AA ({len(aa_seq)} residues)")

            embedding = self.generate_embedding(aa_seq)
            z_score = self.compute_z_score(embedding)
            print(f"  -> Anomaly Z-Score computed: {z_score:.3f}")

            pdb_path = self.generate_and_save_pdb(aa_seq, protein_name)
            print(f"  -> 3D PDB saved permanently to: {pdb_path}")

            sequence_3di = self.convert_pdb_to_3di(pdb_path, protein_name)
            print(f"  -> Extracted 1D 3Di structure string.")

            return {
                "status": "success",
                "protein_name": protein_name,
                "z_score": z_score,
                "sequence_3di": sequence_3di,
            }

        except Exception as e:
            print(f"[Agent 1] ERROR: {e}")
            return {"status": "error", "message": str(e)}


if __name__ == '__main__':
    dna_sequence = 'AAATTCTCTCAGTGGAACATGATCAACAAAGTTGGTCACCGTGTTGAATCTGCGCGTCACCTCCATGTTCTGCAAAAAGACATGGAAAACCTGGAATCTCTGGCGCTGGTTGGTCTGTCTGGCAACGGTTCTGGTGGTAACGGCTCCGGC'
    protein_name = '1BWX_PG_hp'

    agent = MapperAgent()
    status_json = agent.run(dna_sequence, protein_name)

    print(status_json)
